
def advClv():
 while True:
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print("*--------------------------------------------------------------------------------*")
        print("* Bienvenido a \"Adivina el numero\":                                            *")
        print("*                                                                                *")
        print("* Para jugar correctamente pidele a tu amigo que se voltie de espaldas o         *")
        print("* que simplemente no vea el numero que vas a esconderle!, recuerda darle pistas! *")
        print("* y recordarle que solo tiene \"5\" oportunidades para adivinar!                 *")
        print("*                                                                                *")
        print("* A continuacion, escribe el numero que le esconderas a tu amigo!                *")
        print("*--------------------------------------------------------------------------------*")
        print()
        numeroEsconder= int(input("Escribe el numero que le vas a esconder a tu amigo: "))
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        numeroSecreto= int(input("Escribe el numero que escondio tu amigo: "))
        oportunidades = 5
        perm = "si"
        while numeroSecreto != numeroEsconder:
            print()
            if oportunidades >= 1:
                if oportunidades == 1:
                    perm = "no"
                    oportunidades = 0
                if perm == "si":
                    print("No adivinaste el numero? Pidele una pista a tu amigo!...")
                    oportunidades -= 1
                if oportunidades == 1:
                    print("Tienes una oportunidad")
                elif oportunidades == 2:
                    print("Tienes dos oportunidades")
                elif oportunidades == 3:
                    print("Tienes tres oportunidades")
                elif oportunidades == 4:
                    print("Tienes cuatro oportunidades")
                else:
                    print()
                    print("As perdido :(, pero tranquilo tu ponle un numero mas dificil a el! >:D")
                    break
                numeroSecreto = int(input("Escribe otro numero: "))
                print()
        if numeroSecreto == numeroEsconder:
            print()
            print(("Felicidades advivnaste! El numero secreo era: "), (numeroEsconder))
            print()
        print("Quieres jugar otra vez o le toca el turno a tu amigo?")
        print()
        print("Escribe \"Si\" para volver a jugar")
        print("Escribe \"No\" para vovler al menu")
        print()
        abc = input("Escribe aqui: ")
        if abc == "Si":
            continue
        elif abc == "No":
            break
advClv()
