print("*---------------------------------*")
print("* Hola, soy el mago junior        *")
print("*                                 *")
print("* Quieres jugar un juego conmigo? *")
print("* Adivina que numero escondi!     *")
print("*                __               *")
print("*               /  \              *")
print("*              /    \             *")
print("*---------------------------------*")
print()
numeroSecreto = int(input("Escribe el numero secreto: "))
while numeroSecreto != 777:
    print()
    print("No adivinaste el numero? intentalo denuevo...")
    numeroSecreto = int(input("Escribe otro numero: "))
    print()
print()
print("Felicidades advivnaste! El numero secreo era \"777\"")
n = input()
